jobs:
  python36:
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
      - run:
          name: Python 3.6.9 CLI Test
          command: |
            python3 -V
            pip install -e .
            pynamegen debug=True file=classic.txt method=classic
            pynamegen debug=True file=random.txt method=random
  python37:
    docker:
      - image: circleci/python:3.7.7
    steps:
      - checkout
      - run:
          name: Python 3.7.7 CLI Test
          command: |
            python3 -V
            pip install -e .
            pynamegen debug=True file=classic.txt method=classic
            pynamegen debug=True file=random.txt method=random
  python38:
    docker:
      - image: circleci/python:3.8.2
    steps:
      - checkout
      - run:
          name: Python 3.8.2 CLI Test
          command: |
            python3 -V
            pip install -e .
            pynamegen debug=True file=classic.txt method=classic
            pynamegen debug=True file=random.txt method=random
workflows:
  version: 2
  circleci_python3.6:
    jobs:
      - python36
  circleci_python3.7:
    jobs:
      - python37
  circleci_python3.8:
    jobs:
      - python38
