jobs:
  python36:
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
      - run:
          name: Python 3.6.9 CLI Test
          command: |
            python3 -V
            echo "Updating pip..."
            pip install --upgrade --user pip
            echo "Updating Python packages..."
            pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U --user
            echo "Installing pynamegen..."
            pip install --user -e .
            echo "List of installed packages:"
            pip list
            echo "Making citests directory for storing generated names"
            mkdir citests/
            echo "Testing classic method..."
            pynamegen debug=True file=citests/classic.txt method=classic
            echo "Testing random method..."
            pynamegen debug=True file=citests/random.txt method=random
            echo "Testing surprise method..."
            pynamegen debug=True file=citests/surprise.txt method=surprise
            echo "Testing terminal output mode..."
            pynamegen amt=1 debug=False file=stdout method=surprise
      - store_artifacts:
          path: citests/
  python37:
    docker:
      - image: circleci/python:3.7.7
    steps:
      - checkout
      - run:
          name: Python 3.7.7 CLI Test
          command: |
            python3 -V
            echo "Updating pip..."
            pip install --upgrade --user pip
            echo "Updating Python packages..."
            pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U --user
            echo "Installing pynamegen..."
            pip install --user -e .
            echo "List of installed packages:"
            pip list
            echo "Making citests directory for storing generated names"
            mkdir citests/
            echo "Testing classic method..."
            pynamegen debug=True file=citests/classic.txt method=classic
            echo "Testing random method..."
            pynamegen debug=True file=citests/random.txt method=random
            echo "Testing surprise method..."
            pynamegen debug=True file=citests/surprise.txt method=surprise
            echo "Testing terminal output mode..."
            pynamegen amt=1 debug=False file=stdout method=surprise
      - store_artifacts:
          path: citests/
  python38:
    docker:
      - image: circleci/python:3.8.2
    steps:
      - checkout
      - run:
          name: Python 3.8.2 CLI Test
          command: |
            python3 -V
            echo "Updating pip..."
            pip install --upgrade --user pip
            echo "Updating Python packages..."
            pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U --user
            echo "Installing pynamegen..."
            pip install --user -e .
            echo "List of installed packages:"
            pip list
            echo "Making citests directory for storing generated names"
            mkdir citests/
            echo "Testing classic method..."
            pynamegen debug=True file=citests/classic.txt method=classic
            echo "Testing random method..."
            pynamegen debug=True file=citests/random.txt method=random
            echo "Testing surprise method..."
            pynamegen debug=True file=citests/surprise.txt method=surprise
            echo "Testing terminal output mode..."
            pynamegen amt=1 debug=False file=stdout method=surprise
      - store_artifacts:
          path: citests/
workflows:
  version: 2
  circleci_python3:
    jobs:
      - python36
      - python37
      - python38
