jobs:
  python36:
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
      - run:
          name: Python 3.6.9 CLI Test
          command: |
            python3 -V
            pip install --user -e .
            pip list
            pynamegen debug=True file=classic.txt method=classic
            pynamegen debug=True file=random.txt method=random
            pynamegen debug=True file=surprise.txt method=surprise
  python37:
    docker:
      - image: circleci/python:3.7.7
    steps:
      - checkout
      - run:
          name: Python 3.7.7 CLI Test
          command: |
            python3 -V
            pip install --user -e .
            pip list
            pynamegen debug=True file=classic.txt method=classic
            pynamegen debug=True file=random.txt method=random
            pynamegen debug=True file=surprise.txt method=surprise
  python38:
    docker:
      - image: circleci/python:3.8.2
    steps:
      - checkout
      - run:
          name: Python 3.8.2 CLI Test
          command: |
            python3 -V
            pip install --user -e .
            pip list
            pynamegen debug=True file=classic.txt method=classic
            pynamegen debug=True file=random.txt method=random
            pynamegen debug=True file=surprise.txt method=surprise
workflows:
  version: 2
  circleci_python3:
    jobs:
      - python36
      - python37
      - python38
